# Generated by Django 4.1.1 on 2022-11-22 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userchoice_choice_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=datetime.datetime(2022, 11, 22, 11, 34, 57, 353877, tzinfo=datetime.timezone.utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='mini_description',
            field=models.CharField(default=datetime.datetime(2022, 11, 22, 11, 35, 37, 269783, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
