# Generated by Django 4.1.1 on 2022-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_description_question_mini_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='question',
            name='mini_description',
            field=models.CharField(max_length=150),
        ),
    ]
