# Generated by Django 4.1.1 on 2022-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mini_description',
            field=models.CharField(max_length=70),
        ),
    ]
