# Generated by Django 4.1.1 on 2022-11-22 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 11, 22, 12, 38, 1, 231431, tzinfo=datetime.timezone.utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
