# Generated by Django 4.1.1 on 2022-11-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCore',
        ),
    ]
