# Generated by Django 4.1.1 on 2022-11-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0002_rename_user_usercore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCore',
            new_name='User',
        ),
    ]
