# Generated by Django 4.1.1 on 2022-11-21 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0004_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 14, 27, 24, 781314, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
