# Generated by Django 4.1.1 on 2022-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='is_superadmin'),
        ),
    ]
