# Generated by Django 4.1.1 on 2022-11-21 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0008_user_is_active_user_is_staff_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
